language: java
before_script: cqlsh -f cassandra/src/main/dist/schema/tables.cql
script: ./gradlew check
jdk:
  - oraclejdk8
notifications:
  email: false
sudo: false
cache:
  directories:
    - $HOME/.gradle/daemon/
    - $HOME/.gradle/native/
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/caches/2.5
branches:
  only:
    - master
services:
  - cassandra
