language: java
before_script: cqlsh -f cassandra/src/main/dist/config/tables.cql
script: ./gradlew check
jdk:
  - oraclejdk8
notifications:
  email: false
sudo: false
cache:
  directories:
    - $HOME/.gradle/wrapper/dists/gradle-2.5-bin/
branches:
  only:
    - master
services:
  - cassandra
