language: java
before_script: ./gradlew testClasses
script: ./gradlew checkstyleMain checkstyleTest checkstyleJmh
jdk:
  - oraclejdk8
notifications:
  email: false
sudo: false
cache:
  directories:
    - $HOME/.gradle/
