language: java
before_script: ./gradlew assemble
script: ./gradlew checkstyleMain checkstyleTest checkstyleJmh
jdk:
  - oraclejdk8
notifications:
  email: false
sudo: false
cache:
  directories:
    - $HOME/.gradle/
branches:
  only:
    - master
